### ISSUE TITLE
Cannot enbale the add-on

### ISSUE THREAD

**Issue by ElnRay** [trzr/Blender-CM3D2-BoneUtil#2]
![2020-05-20 (2)](https://user-images.githubusercontent.com/23614048/82355508-e0e06280-9a34-11ea-86c1-2c79a0a49327.png)
The blend version is 2.8.2
I hope you can fix it!

**Comment by ElnRay** [comment]
Solved it by renaming the folder "CM3D2_BoneUtil" to "CM3D2 BoneUtil".

**Comment by trzr** [comment]
hmm...
I tried it in the blender-2.82a environment, but the problem does not occur.

**Comment by ElnRay** [comment]
> hmm...
> I tried it in the blender-2.82a environment, but the problem does not occur.

I solved it by renaming the folder "CM3D2_BoneUtil" to "CM3D2 BoneUtil". Thank you.
